language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
addons:
  firefox: "38.0"
before_install:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: npm run test-single-run
